"""Receipted one-time speech assets for real context-search progress."""
import argparse
import json
from pathlib import Path
import shutil
import sys
from generate_progress import MODEL, ROOT, SOURCES, digest, encode, json_write, run, save_pcm, trim_edges, wav_pcm


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--out', type=Path, required=True)
    p.add_argument('--execute', action='store_true')
    p.add_argument('--kind', choices=('search', 'completion', 'memory'), default='search')
    p.add_argument('--sample-rate',type=int,choices=(16000,24000),default=16000)
    args = p.parse_args()
    ffmpeg = shutil.which('ffmpeg')
    if not ffmpeg:
        raise RuntimeError('ffmpeg is required')
    args.out.mkdir(parents=True, exist_ok=True)
    runner = [sys.executable, '-X', 'utf8', Path.home()/'.codex/skills/qianwen-model-suite/scripts/qianwen.py']
    kind=args.kind
    rate=args.sample_rate
    if kind!='completion' and rate!=16000:
        raise ValueError('Search/memory assets require 16 kHz')
    budget=(32 if kind=='completion' else 16 if kind=='memory' else 24)*1024
    phrases=(['灯光设置好了。', '灯光设定好喇。'] if kind=='completion' else
             ['我来保存。', '我记低先。'] if kind=='memory' else
             ['我在查之前的记录。', '我而家查紧之前嘅记录。'])
    manifest = dict(model=MODEL, synthetic=True, source=SOURCES, kind=kind,
                    sample_rate=rate, budget_bytes=budget, complete=False, clips=[])
    output = ['/* Generated by tools/voice/generate_stage_progress.py; see asset receipts. */']
    if kind=='completion':output.append(f'enum {{ COMPLETION_RATE={rate} }};')
    total = 0
    for name, text, voice in [(kind+'_zh', phrases[0], 'Cherry'),
                              (kind+'_yue', phrases[1], 'Kiki')]:
        folder = args.out/name
        folder.mkdir(exist_ok=True)
        task = dict(capability='tts-qwen', request=dict(model=MODEL,
                    input=dict(text=text, voice=voice, language_type='Chinese')))
        task_path = folder/'task.json'
        if task_path.exists() and json.loads(task_path.read_text(encoding='utf8')) != task:
            raise RuntimeError('Existing task differs; do not resubmit it')
        json_write(task_path, task)
        run(runner+['plan', '--task', task_path], folder/'plan.log')
        state_path = folder/'job/state.json'
        if not state_path.exists():
            if not args.execute:
                print(name+': planned only', flush=True)
                continue
            run(runner+['run', '--task', task_path, '--state-dir', folder/'job', '--execute'], folder/'run.log')
        state = json.loads(state_path.read_text(encoding='utf8'))
        if state['status'] != 'succeeded':
            raise RuntimeError('Preserved non-successful receipt; no automatic retry')
        run(runner+['collect', '--state-dir', folder/'job'], folder/'collect.log')
        assets = json.loads((folder/'job/artifacts/assets.json').read_text(encoding='utf8'))['files']
        if len(assets) != 1:
            raise ValueError('Expected one audio file')
        original = folder/'job/artifacts'/assets[0]['file']
        canonical = folder/f'original-{rate}.wav'
        run([ffmpeg, '-v', 'error', '-y', '-i', original, '-ac', '1', '-ar', str(rate),
             '-c:a', 'pcm_s16le', canonical], folder/'resample.log')
        trimmed, trim = trim_edges(wav_pcm(canonical, rate))
        save_pcm(folder/'trimmed.wav', trimmed, rate)
        raw, info = encode(ffmpeg, folder, 1.15, rate)
        if info['seconds'] > 3 or total+len(raw) > budget:
            raise ValueError('Stage phrase exceeds the bounded asset budget')
        receipt = json.loads((folder/'job/result.private.json').read_text(encoding='utf8'))
        manifest['clips'].append(dict(name=name, text=text, voice=voice, trim=trim, **info,
            original_sha256=digest(original), provider_request_id=receipt.get('request_id'),
            task_sha256=digest(task_path), billable_posts=state.get('billable_posts')))
        total += len(raw)
        output += [f'static const uint8_t {name}[] = {{']
        output += ['    '+','.join(f'0x{x:02x}' for x in raw[i:i+20])+',' for i in range(0,len(raw),20)]
        output += ['};', f'enum {{ {name.upper()}_SAMPLES={info["samples"]}, {name.upper()}_BLOCK={info["block_bytes"]} }};']
        print(f'{name}: {info["seconds"]:.3f}s, {len(raw)}B', flush=True)
    if len(manifest['clips']) == 2:
        source = ROOT/f'plugins/audio/{kind}_assets.h'
        output += [f'_Static_assert(sizeof({kind}_zh)+sizeof({kind}_yue)<={budget}u,"Speech asset budget");']
        source.write_text('\n'.join(output)+'\n', encoding='utf8')
        manifest.update(complete=True, asset_bytes=total, header_sha256=digest(source))
    json_write(args.out/'manifest.json', manifest)


if __name__ == '__main__':
    main()
