#include "kws_fusion.h"
#include "kws_internal.h"
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>

static void i8(const char *name,const int8_t *p,size_t n)
{
    printf(".%s={",name);
    for(size_t i=0;i<n;++i)printf("%s%d%s",i?",":"",p[i],i%32==31?"\n":"");
    puts("},");
}
static void i16(const char *name,const int16_t *p,size_t n)
{
    printf(".%s={",name);
    for(size_t i=0;i<n;++i)printf("%s%d%s",i?",":"",p[i],i%32==31?"\n":"");
    puts("},");
}
static void neural(const char *name,const kws_neural_t *s)
{
    printf(".%s={\n",name);i8("history",s->history,sizeof(s->history));
    printf(".position={");for(unsigned i=0;i<6;++i)printf("%s%u",i?",":"",s->position[i]);puts("},");
    i8("current",s->current,sizeof(s->current));i8("next",s->next,sizeof(s->next));puts("},");
}
int main(void)
{
    void *memory=malloc(kws_fusion_size());assert(memory);
    kws_fusion_t *s=NULL;
    assert(!kws_fusion_init(memory,kws_fusion_size(),&kws_trained_model,&kws_secondary_model,&s));
    const int16_t zero[256]={0};kws_event_t event;
    for(unsigned frame=1;frame<=128;++frame) {
        assert(!kws_fusion_step_pcm(s,zero,(uint64_t)frame*256,&event,NULL));
        assert(!event.detected);
    }
    assert(s->last_sample==32768 && s->detector.blocks==64 && !s->detector.votes && !s->detector.cooldown_until);
    puts("/* Generated by tools/kws/export_silence.c; hashes in silence_el.cmake. */");
    puts("static const kws_silence_seed_t kws_silence_el={");
    i16("previous",s->first.previous,256);neural("first",&s->first.neural);neural("second",&s->second);
    printf(".detector={.last_sample=%llu,.cooldown_until=%llu,.blocks=%u,.votes=%u,.threshold_q8=%d},\n",
        (unsigned long long)s->detector.last_sample,(unsigned long long)s->detector.cooldown_until,
        s->detector.blocks,s->detector.votes,s->detector.threshold_q8);
    printf(".last_sample=%llu,\n",(unsigned long long)s->last_sample);
    i16("recent",s->recent,3);i16("scores",s->scores,2);
    printf(".score=%d,.next=%u,.count=%u,.half=%u\n};\n",s->score,s->next,s->count,s->half);
    puts("_Static_assert(sizeof(kws_silence_el)<=7168,\"E/L seed Flash budget\");");
    fprintf(stderr,"frames=128 synthetic_samples=32768 state_flash_bytes=%zu workspace_bytes=%zu\n",sizeof(kws_silence_seed_t),kws_fusion_size());
    free(memory);return 0;
}
