"""Deterministic GRU activation table; Decimal is host-only, no vendor code."""
from decimal import Decimal, localcontext, ROUND_HALF_UP
from pathlib import Path
import argparse


def values():
    with localcontext() as context:
        context.prec=80
        return [int((Decimal(32768)/(1+(-Decimal(i)/16).exp())).to_integral_value(rounding=ROUND_HALF_UP))
                for i in range(-256,257)]


def source():
    table=values()
    lines=['/* Generated by tools/kws/generate_gru_sigmoid.py; ABI v1, Q15. */',
           'static const uint16_t gru_sigmoid[513] = {']
    lines+=['    '+','.join(map(str,table[i:i+16]))+',' for i in range(0,len(table),16)]
    return '\n'.join(lines+['};',''])


if __name__=='__main__':
    parser=argparse.ArgumentParser()
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    root=Path(__file__).resolve().parents[2]
    target=root/'components/kws_c11/generated/gru32_sigmoid.inc'
    if args.check:
        if target.read_text(encoding='utf8')!=source():
            raise SystemExit('Stale recurrent activation table')
    else:
        target.write_text(source(),encoding='utf8',newline='\n')
