"""Generate an E/L C11 silent-state initializer with source SHA256 binding.

Run under WSL: python3 tools/kws/generate_silence.py
No training, audio device, model service or target device access is performed.
"""
from pathlib import Path
import argparse
import hashlib
import json
import subprocess

ROOT = Path(__file__).resolve().parents[2]
KWS = ROOT / 'components/kws_c11'
SOURCES = [
    'components/kws_c11/generated/fusion_primary.c',
    'components/kws_c11/generated/fusion_secondary_l.c',
    'components/kws_c11/generated/tables.c',
    'components/kws_c11/generated/fft_config.inc',
    'components/kws_c11/kws_internal.h',
    'components/kws_c11/kws_buffers.h',
    'components/kws_c11/include/kws.h',
    'components/kws_c11/include/kws_fusion.h',
    'components/kws_c11/kws_fusion.c',
    'components/kws_c11/kws_detector.c',
    'components/kws_c11/kws_nn.c',
    'components/kws_c11/kws_frontend.c',
    'components/kws_c11/kws_fft.c',
    'components/kws_c11/kws_quant.c',
    'tools/kws/export_silence.c',
    'third_party/kissfft/kiss_fft.h',
    'third_party/kissfft/kiss_fft.c',
    'third_party/kissfft/_kiss_fft_guts.h',
]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--build', type=Path, default=ROOT / 'artifacts/voice-fast/kws-silence-export')
    parser.add_argument('--check', action='store_true', help='Compare regenerated files without changing them')
    args = parser.parse_args()
    subprocess.run(['cmake', '-S', str(ROOT/'tests/kws'), '-B', str(args.build),
                    '-G', 'Ninja', '-DKWS_VERIFY_SILENCE_SEED=OFF'], check=True)
    subprocess.run(['cmake', '--build', str(args.build), '--target', 'kws_export_silence'], check=True)
    run = subprocess.run([str(args.build/'kws_export_silence')], check=True, stdout=subprocess.PIPE)
    seed = KWS/'generated/silence_el.inc'
    hashes = {name: hashlib.sha256((ROOT/name).read_bytes()).hexdigest() for name in SOURCES}
    hashes[seed.relative_to(ROOT).as_posix()] = hashlib.sha256(run.stdout).hexdigest()
    manifest = dict(format='kws.el.silence/1', frames=128, frame_samples=256,
                    synthetic_samples=32768, frontend='fixed_logmel_no_pcen', hashes=hashes)
    script = ['# Generated by tools/kws/generate_silence.py. Stale seeds fail the build.',
              'get_filename_component(KWS_SEED_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)',
              'function(kws_seed_check relative expected)',
              '  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${KWS_SEED_ROOT}/${relative}")',
              '  file(SHA256 "${KWS_SEED_ROOT}/${relative}" actual)',
              '  if(NOT actual STREQUAL expected)',
              '    message(FATAL_ERROR "E/L silence seed is stale: ${relative}. Run tools/kws/generate_silence.py")',
              '  endif()', 'endfunction()']
    script += [f'kws_seed_check("{name}" "{value}")' for name, value in hashes.items()]
    files = {seed: run.stdout,
             KWS/'generated/silence_el.json': (json.dumps(manifest, indent=2)+'\n').encode(),
             KWS/'generated/silence_el.cmake': ('\n'.join(script)+'\n').encode()}
    for path, data in files.items():
        if args.check:
            if not path.exists() or path.read_bytes() != data:
                raise SystemExit(f'Generated seed differs: {path}')
        else:
            path.write_bytes(data)
    print('E/L silent seed matches' if args.check else 'E/L silent seed generated')


if __name__ == '__main__':
    main()
