"""Stage the bounded L candidate with provenance; never flash or change E/K."""
import hashlib
import json
from pathlib import Path
import sys

ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'training/kws'))
from calibrate import emit_c


def digest(path):return hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    base=ROOT/'artifacts/kws-bilingual'
    generated=ROOT/'components/kws_c11/generated'
    release=ROOT/'training/kws/releases/compact-l'
    release.mkdir(parents=True,exist_ok=True)
    model=json.loads((base/'adapt-l-int8/model.json').read_text())
    parity=json.loads((base/'parity-l/host-parity.json').read_text())
    assert parity['passed'] and parity['model_json_sha256']==digest(base/'adapt-l-int8/model.json')
    assert model['checkpoint_sha256']==digest(base/'adapt-l/best.pt')
    evaluation=json.loads((base/'evaluation.json').read_text())
    assert evaluation['complete'] and not evaluation['threshold_retuned']
    retained={name:digest(generated/name) for name in ('fusion_primary.c','fusion_secondary_k.c')}
    source=emit_c(model,'kws_secondary_model')
    assert source==(base/'adapt-l-int8/model_secondary.c').read_text()
    (generated/'fusion_secondary_l.c').write_text(source,encoding='utf8',newline='\n')
    (generated/'fusion_secondary_l.json').write_bytes((base/'adapt-l-int8/model.json').read_bytes())
    copies={
        'training-config.json':'adapt-l/config.json',
        'training-history.json':'adapt-l/history.json',
        'training-data-provenance.json':'features-compact/features.json',
        'synthesis-manifest.jsonl':'compact-tts-02/data/dataset-zh-compact2.jsonl',
        'automatic-pronunciation-screen.json':'compact-asr.json',
        'host-parity.json':'parity-l/host-parity.json',
        'validation-comparison.json':'evaluation.json',
        'sapi-baseline.json':'sapi-probe-02/baseline-deduplicated.json',
        'sapi-candidate.json':'sapi-probe-02/candidate-el.json',
        'replay-selection.jsonl':'replay-selection.jsonl',
    }
    for destination,source_path in copies.items():
        (release/destination).write_bytes((base/source_path).read_bytes())
    config=json.loads((base/'adapt-l/config.json').read_text())
    manifest=dict(name='xiaoyan_ds_tcn24_el3',pair='el',default_pair='ek',experimental=True,
        primary_model='E',secondary_model='L',threshold_per_mille=740,smoothing_blocks=3,
        coefficients=[1,1],workspace_bytes=12632,parameters_per_member=6673,
        checkpoint_step=model['training_step'],checkpoint_sha256=model['checkpoint_sha256'],
        parent_checkpoint_sha256=config['initial_checkpoint_sha256'],parent_candidate='K',
        training_steps=2000,training_seed=202609221,training_source_hashes=config['training_source_hashes'],
        model_json_sha256=digest(generated/'fusion_secondary_l.json'),
        c_sha256=digest(generated/'fusion_secondary_l.c'),retained_model_sha256=retained,
        files={name:digest(release/name) for name in copies},
        known_regression='One additional FLEURS Cantonese natural-speech false trigger: 4/636 -> 5/636 on development validation.',
        accepted_scope='Comparison candidate for same-device acoustic validation; no human generalization claim.',
        synthesis=dict(engine='local CosyVoice2',source_commit='bea884c67f03f73f2d2d94557457a5849dd61090',
            model_revision='eec1ae6c79877dbd9379285cf8789c9e0879293d',license='Apache-2.0',
            reference_revision='f3ff3571791e39611d31c381e3a41a3af07b4987'),
        reproducibility='Exported C/JSON and metadata are in source. Exact re-training additionally requires ignored local source WAVs, frozen base features and K checkpoint listed by hashes; they are not downloaded or regenerated by building firmware.')
    (release/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
    assert retained=={name:digest(generated/name) for name in retained}
    print(json.dumps(dict(staged=True,pair='el',default_pair='ek',model_json_sha256=manifest['model_json_sha256'],c_sha256=manifest['c_sha256'])))


if __name__=='__main__':main()
