#include "kws_conditioned_seed.h"
#include <string.h>

/* Generated by seed_export.c from these exact models, frontend and controller.
 * The consuming build must freeze their hashes with the generated include. */
#include "kws_conditioned_seed.inc"

uint64_t kws_conditioned_seed_prime(kws_conditioned_runtime_t *s)
{
    if (!s || s->first.model != &kws_frozen_primary ||
        s->secondary_model != &kws_frozen_secondary || s->verifier_model != &kws_trained_model ||
        s->last_sample || s->half || s->count || s->next || s->decision.original.blocks ||
        s->decision.original.threshold_q8 || s->decision.original.stable ||
        s->decision.pending || s->decision.last_support || s->decision.verify_votes) return 0;
    s->primary = kws_conditioned_silence.primary;
    s->secondary = kws_conditioned_silence.secondary;
    s->verifier = kws_conditioned_silence.verifier;
    s->decision = kws_conditioned_silence.decision;
    s->last_sample = kws_conditioned_silence.last_sample;
    memcpy(s->recent, kws_conditioned_silence.recent, sizeof(s->recent));
    memcpy(s->heads, kws_conditioned_silence.heads, sizeof(s->heads));
    memcpy(s->score, kws_conditioned_silence.score, sizeof(s->score));
    s->next = kws_conditioned_silence.next;
    s->count = kws_conditioned_silence.count;
    s->half = kws_conditioned_silence.half;
    return s->last_sample;
}

size_t kws_conditioned_seed_bytes(void) { return sizeof(kws_conditioned_silence); }
