"""Regenerate finite-harmonic 256-sample music waves (host floating point only)."""
import math
from pathlib import Path

# Bass retains its fundamental while exposing more upper partials on the small speaker.
profiles = [(0.78,0.16,0.055,0.005), (0.25,0.35,0.25,0.15), (0.58,0.26,0.10,0.06)]
lines = ["/* Generated by tools/generate_music_tables.py; four harmonics stay below Nyquist at MIDI 96. */",
         "static const int16_t song_waves[3][256] = {"]
for weights in profiles:
    values = [sum(w*math.sin((h+1)*2*math.pi*i/256) for h,w in enumerate(weights)) for i in range(256)]
    peak = max(abs(x) for x in values)
    data = [round(x/peak*32700) for x in values]
    lines.append("    {")
    for i in range(0,256,16):
        lines.append("        " + ",".join(str(x) for x in data[i:i+16]) + ",")
    lines.append("    },")
lines.append("};")
Path("plugins/audio/song_waves.h").write_text("\n".join(lines)+"\n",encoding="utf-8")
