# Insert scheduling points in one pinned outer loop; crypto and TLS decisions
# remain in the vendor implementation. The installed SDK is never modified.
function(agent_configure_tls_cooperation tls_target)
  get_target_property(agent_tls_dir ${tls_target} SOURCE_DIR)
  set(agent_tls_source "${agent_tls_dir}/ssl_tls.c")
  file(READ "${agent_tls_source}" agent_tls_text)
  string(REPLACE "\r\n" "\n" agent_tls_text "${agent_tls_text}")
  string(SHA256 agent_tls_hash "${agent_tls_text}")
  if(NOT agent_tls_hash STREQUAL "1beac5da2dd0f99f626c81651e9cecb921eb9725a9f17624851802b8c6259ddc")
    message(FATAL_ERROR "Review the pinned TLS outer loop before changing its cooperation adapter")
  endif()
  set(agent_tls_step "        ret = mbedtls_ssl_handshake_step(ssl);")
  string(REGEX MATCHALL "ret = mbedtls_ssl_handshake_step\\(ssl\\)" agent_tls_matches "${agent_tls_text}")
  list(LENGTH agent_tls_matches agent_tls_count)
  if(NOT agent_tls_count EQUAL 1)
    message(FATAL_ERROR "Expected exactly one outer TLS handshake-step call")
  endif()
  string(REPLACE "${agent_tls_step}"
    "        agent_tls_cooperate_step(0);\n${agent_tls_step}\n        agent_tls_cooperate_step(1);"
    agent_tls_adapted "${agent_tls_text}")
  if(agent_tls_adapted STREQUAL agent_tls_text)
    message(FATAL_ERROR "TLS cooperation insertion did not match")
  endif()
  get_target_property(agent_tls_sources ${tls_target} SOURCES)
  set(agent_tls_replaced 0)
  foreach(agent_source IN LISTS agent_tls_sources)
    get_filename_component(agent_name "${agent_source}" NAME)
    if(agent_name STREQUAL "ssl_tls.c")
      list(REMOVE_ITEM agent_tls_sources "${agent_source}")
      math(EXPR agent_tls_replaced "${agent_tls_replaced}+1")
    endif()
  endforeach()
  if(NOT agent_tls_replaced EQUAL 1)
    message(FATAL_ERROR "Expected one pinned TLS translation unit")
  endif()
  set(agent_tls_wrapper "${CMAKE_BINARY_DIR}/agent_tls_cooperate_sdk.c")
  file(WRITE "${agent_tls_wrapper}" "extern void agent_tls_cooperate_step(int finished);\n${agent_tls_adapted}")
  set_property(TARGET ${tls_target} PROPERTY SOURCES ${agent_tls_sources} "${agent_tls_wrapper}")
endfunction()
